[tool.poetry]
name = "pysifen"
version = "0.1.0"
description = ""
authors = ["josecuev <jmcuev89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
